import { KeyRound, Pencil, Power, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { StatusBadge } from '@/components/common/StatusBadge'
import { TenantTypeBadge } from '@/components/common/TenantTypeBadge'
import type { SuperAdminUser } from '@/types/superadmin'
import { formatDate } from '@/utils/formatDate'

export const UsersTable = ({ users, onEdit, onToggle, onReset, onDelete }: { users: SuperAdminUser[]; onEdit: (user: SuperAdminUser) => void; onToggle: (user: SuperAdminUser) => void; onReset: (user: SuperAdminUser) => void; onDelete: (user: SuperAdminUser) => void }) =>
  <div className="overflow-x-auto rounded-2xl border bg-white shadow-panel"><table className="w-full min-w-[960px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-4 py-3">User</th><th className="px-4 py-3">Business</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Role</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Password</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{users.map((user) => <tr key={user.id} className="border-t"><td className="px-4 py-3"><b>{user.name}</b><p className="text-xs text-slate-400">{user.email}</p></td><td className="px-4 py-3">{user.tenantName || '-'}</td><td className="px-4 py-3">{user.tenantType ? <TenantTypeBadge type={user.tenantType} /> : '-'}</td><td className="px-4 py-3 capitalize">{user.role}</td><td className="px-4 py-3"><StatusBadge status={user.status} /></td><td className="px-4 py-3"><StatusBadge status={user.passwordResetRequired ? 'pending' : 'active'} /></td><td className="px-4 py-3">{formatDate(user.createdAt)}</td><td className="px-4 py-3"><div className="flex gap-1"><Button size="icon" variant="ghost" title="Edit" onClick={() => onEdit(user)}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" title="Activate or deactivate" onClick={() => onToggle(user)}><Power className="h-4 w-4" /></Button><Button size="icon" variant="ghost" title="Reset password" onClick={() => onReset(user)}><KeyRound className="h-4 w-4" /></Button><Button size="icon" variant="ghost" title="Delete" className="text-red-600" onClick={() => onDelete(user)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div>
