import { CreditCard, Eye, PauseCircle, PlayCircle, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { Button } from '@/components/ui/button'
import { StatusBadge } from '@/components/common/StatusBadge'
import { TenantTypeBadge } from '@/components/common/TenantTypeBadge'
import type { Tenant } from '@/types/superadmin'
import { formatDate } from '@/utils/formatDate'

export const TenantTable = ({ tenants, onPayment, onStatus, onDelete }: { tenants: Tenant[]; onPayment: (tenant: Tenant) => void; onStatus: (tenant: Tenant) => void; onDelete: (tenant: Tenant) => void }) =>
  <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white shadow-panel"><table className="min-w-[1150px] w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-400"><tr><th className="px-4 py-3">Business</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Phone</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Subscription</th><th className="px-4 py-3">Payment</th><th className="px-4 py-3">Created</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{tenants.map((tenant) => <tr key={`${tenant.type}-${tenant.id}`} className="border-t border-slate-100"><td className="px-4 py-3"><p className="font-bold text-slate-800">{tenant.name}</p><p className="text-xs text-slate-400">{tenant.slug}</p></td><td className="px-4 py-3"><TenantTypeBadge type={tenant.type} /></td><td className="px-4 py-3"><p>{tenant.ownerName || '-'}</p><p className="text-xs text-slate-400">{tenant.ownerEmail || '-'}</p></td><td className="px-4 py-3">{tenant.phone || '-'}</td><td className="px-4 py-3"><StatusBadge status={tenant.status} /></td><td className="px-4 py-3"><p>{tenant.subscription?.plan || '-'}</p><StatusBadge status={tenant.subscription?.status} /></td><td className="px-4 py-3"><StatusBadge status={tenant.payment?.isConfigured ? 'active' : 'inactive'} /></td><td className="px-4 py-3">{formatDate(tenant.createdAt)}</td><td className="px-4 py-3"><div className="flex gap-1"><Button asChild variant="ghost" size="icon"><Link to={`/tenants/${tenant.id}?type=${tenant.type}`}><Eye className="h-4 w-4" /></Link></Button><Button variant="ghost" size="icon" onClick={() => onPayment(tenant)}><CreditCard className="h-4 w-4" /></Button><Button variant="ghost" size="icon" onClick={() => onStatus(tenant)}>{tenant.status === 'active' ? <PauseCircle className="h-4 w-4" /> : <PlayCircle className="h-4 w-4" />}</Button><Button variant="ghost" size="icon" className="text-red-600" onClick={() => onDelete(tenant)}><Trash2 className="h-4 w-4" /></Button></div></td></tr>)}</tbody></table></div>
