import { Eye, PlayCircle, RefreshCcw, ShieldBan } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { StatusBadge } from '@/components/common/StatusBadge'
import { TenantTypeBadge } from '@/components/common/TenantTypeBadge'
import type { Subscription } from '@/types/superadmin'
import { formatDate } from '@/utils/formatDate'

export const SubscriptionsTable = ({ subscriptions, onAction }: { subscriptions: Subscription[]; onAction: (subscription: Subscription, action: 'renew' | 'suspend' | 'activate') => void }) =>
  <div className="overflow-x-auto rounded-2xl border bg-white shadow-panel"><table className="w-full min-w-[950px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="px-4 py-3">Business</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Owner</th><th className="px-4 py-3">Plan</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Start</th><th className="px-4 py-3">Expiry</th><th className="px-4 py-3">Overdue</th><th className="px-4 py-3">Actions</th></tr></thead><tbody>{subscriptions.map((subscription) => <tr key={subscription.id} className="border-t"><td className="px-4 py-3 font-bold">{subscription.tenantName}</td><td className="px-4 py-3"><TenantTypeBadge type={subscription.tenantType} /></td><td className="px-4 py-3">{subscription.ownerName || '-'}</td><td className="px-4 py-3">{subscription.plan}</td><td className="px-4 py-3"><StatusBadge status={subscription.status} /></td><td className="px-4 py-3">{formatDate(subscription.startDate)}</td><td className="px-4 py-3">{formatDate(subscription.expiryDate)}</td><td className="px-4 py-3">{subscription.overdueDays || 0} days</td><td className="px-4 py-3"><div className="flex gap-1"><Button size="icon" variant="ghost" title="View"><Eye className="h-4 w-4" /></Button><Button size="icon" variant="ghost" title="Renew" onClick={() => onAction(subscription, 'renew')}><RefreshCcw className="h-4 w-4" /></Button>{subscription.status === 'suspended' ? <Button size="icon" variant="ghost" title="Activate" onClick={() => onAction(subscription, 'activate')}><PlayCircle className="h-4 w-4" /></Button> : <Button size="icon" variant="ghost" title="Suspend" className="text-red-600" onClick={() => onAction(subscription, 'suspend')}><ShieldBan className="h-4 w-4" /></Button>}</div></td></tr>)}</tbody></table></div>
